name: dune_core_flutter
description: Flutter validation app for package:tailscale.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  demo_core:
    path: ../demo_core
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
